# Generated by Django 3.2.9 on 2022-10-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peaple',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
